# Generated by Django 5.1.5 on 2025-02-05 16:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='relationship',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
