# Generated by Django 5.1.5 on 2025-02-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='teacher',
        ),
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ManyToManyField(blank=True, null=True, related_name='groups', to='teachers.teacher'),
        ),
    ]
