# Generated by Django 5.1.5 on 2025-02-05 06:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_rename_teacher_group_teachers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('ac', 'Active'), ('in', 'Inactive'), ('pd', 'Pending')], default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
    ]
