# Generated by Django 5.1.5 on 2025-02-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_group_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='schedule',
            field=models.CharField(choices=[('mr', 'Morning Session'), ('af', 'Afternoon Session'), ('ev', 'Evening Session')], default='in', max_length=2),
        ),
    ]
