# Generated by Django 5.1.5 on 2025-02-02 14:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_remove_subject_prerequisites_subject_prerequisites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='prerequisites',
        ),
        migrations.AddField(
            model_name='subject',
            name='prerequisites',
            field=models.CharField(choices=[('math', 'Basic Mathematics'), ('physics', 'Introduction to Physics'), ('chemistry', 'Basic Chemistry'), ('english', 'English Language')], default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
