# Generated by Django 5.1.5 on 2025-02-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_remove_subject_prerequisites_subject_prerequisites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='prerequisites',
            field=models.CharField(max_length=255),
        ),
    ]
